name: "Astro Deploy"
description: "A composite action that prepares your Astro site to be deployed to GitHub Pages"
branding:
  icon: "arrow-up-right"
  color: "purple"
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    - uses: pnpm/action-setup@v6
      name: Install pnpm
      with:
        cache: true
    - name: Install dependencies
      shell: bash
      run: pnpm install
    - name: Restore Astro cache
      id: astro-cache-restore
      uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ./node_modules/.astro
        key: astro-cache-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          astro-cache-${{ runner.os }}-
    - name: Test
      shell: bash
      run: pnpm test
    - name: Build
      shell: bash
      run: pnpm build
    - name: Save Astro cache
      if: ${{ steps.astro-cache-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ./node_modules/.astro
        key: ${{ steps.astro-cache-restore.outputs.cache-primary-key }}
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
      with:
        path: "./dist"
        include-hidden-files: true
