import type { ServoMotor } from './types';

export const BUILTIN_SERVO_MOTORS: ReadonlyArray<ServoMotor> = [
  {
    id: 'jmc-ihss57-200w',
    name: 'JMC iHSS57 (200W)',
    manufacturer: 'JMC',
    motorType: 'step-servo',
    series: 'iHSS',
    model: 'iHSS57',
    ratedRPM: 3000,
    maxRPM: 4500,
    ratedTorque_Nm: 0.64,
    peakTorque_Nm: 1.92,
    continuousPower_W: 200,
    inertia_kgm2: 1.7e-5,
    mass_kg: 0.9,
    frameSize_mm: 57,
    flange_mm: 57,
    voltage_V: 48,
    datasheetPath: 'docs/motors/jmc/ihss-series/jmc-integrated-motor.pdf',
    datasheetUrl: 'https://www.rocketronics.de/download/datasheet/iHSS/JMC-integrated-motor.pdf',
    sourceNote: 'JMC integrated motor family PDF; existing calculator reference model retained.',
    notes: 'Integrated step-servo package.',
    source: 'builtin',
  },
  {
    id: 'jmc-ihss57-400w',
    name: 'JMC iHSS57 (400W)',
    manufacturer: 'JMC',
    motorType: 'step-servo',
    series: 'iHSS',
    model: 'iHSS57',
    ratedRPM: 3000,
    maxRPM: 4500,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 3.81,
    continuousPower_W: 400,
    inertia_kgm2: 2.9e-5,
    mass_kg: 1.2,
    frameSize_mm: 57,
    flange_mm: 57,
    voltage_V: 48,
    datasheetPath: 'docs/motors/jmc/ihss-series/jmc-integrated-motor.pdf',
    datasheetUrl: 'https://www.rocketronics.de/download/datasheet/iHSS/JMC-integrated-motor.pdf',
    sourceNote: 'JMC integrated motor family PDF; existing calculator reference model retained.',
    notes: 'Integrated step-servo package.',
    source: 'builtin',
  },
  {
    id: 'jmc-ihss86-750w',
    name: 'JMC iHSS86 (750W)',
    manufacturer: 'JMC',
    motorType: 'step-servo',
    series: 'iHSS',
    model: 'iHSS86',
    ratedRPM: 3000,
    maxRPM: 4500,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 7.17,
    continuousPower_W: 750,
    inertia_kgm2: 8e-5,
    mass_kg: 2.8,
    frameSize_mm: 86,
    flange_mm: 86,
    voltage_V: 220,
    datasheetPath: 'docs/motors/jmc/ihss-series/jmc-integrated-motor.pdf',
    datasheetUrl: 'https://www.rocketronics.de/download/datasheet/iHSS/JMC-integrated-motor.pdf',
    sourceNote: 'JMC integrated motor family PDF; existing calculator reference model retained.',
    notes: 'Integrated step-servo package.',
    source: 'builtin',
  },
  {
    id: 'jmc-ihss86-1000w',
    name: 'JMC iHSS86 (1000W)',
    manufacturer: 'JMC',
    motorType: 'step-servo',
    series: 'iHSS',
    model: 'iHSS86',
    ratedRPM: 3000,
    maxRPM: 4500,
    ratedTorque_Nm: 3.18,
    peakTorque_Nm: 9.54,
    continuousPower_W: 1000,
    inertia_kgm2: 1.1e-4,
    mass_kg: 3.5,
    frameSize_mm: 86,
    flange_mm: 86,
    voltage_V: 220,
    datasheetPath: 'docs/motors/jmc/ihss-series/jmc-integrated-motor.pdf',
    datasheetUrl: 'https://www.rocketronics.de/download/datasheet/iHSS/JMC-integrated-motor.pdf',
    sourceNote: 'JMC integrated motor family PDF; existing calculator reference model retained.',
    notes: 'Integrated step-servo package.',
    source: 'builtin',
  },
  {
    id: 'omc-a6m60-400h2a1-m17',
    name: 'OMC A6M60-400H2A1-M17 (400W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'A6',
    model: 'A6M60-400H2A1-M17',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 4.45,
    continuousPower_W: 400,
    inertia_kgm2: 5.9e-5,
    mass_kg: 1.3,
    frameSize_mm: 60,
    flange_mm: 60,
    shaftDiameter_mm: 14,
    voltage_V: 220,
    current_A: 2.51,
    poleCount: 10,
    encoder: '17-bit single-turn magnetic absolute',
    protectionRating: 'IP67',
    resistance_ohm: 1.83,
    inductance_mH: 5.6,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/a6-series-400w-ethercat-ac-servo-motor-kit-3000rpm-1-27nm-17-bit-absolute-encoder-ip67-a6-ec400h2a1-m17',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'omc-a6m80-750h2a1-m17',
    name: 'OMC A6M80-750H2A1-M17 (750W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'A6',
    model: 'A6M80-750H2A1-M17',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 8.36,
    continuousPower_W: 750,
    inertia_kgm2: 1.72e-4,
    mass_kg: 2.3,
    frameSize_mm: 80,
    flange_mm: 80,
    shaftDiameter_mm: 19,
    voltage_V: 220,
    current_A: 4.6,
    poleCount: 10,
    encoder: '17-bit single-turn magnetic absolute',
    protectionRating: 'IP67',
    resistance_ohm: 0.47,
    inductance_mH: 2.8,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/a6-series-750w-ethercat-ac-servo-motor-kit-3000rpm-2-39nm-17-bit-absolute-encoder-ip67-a6-ec750h2a1-m17',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'omc-a6m80-1000h2a1-m17',
    name: 'OMC A6M80-1000H2A1-M17 (1000W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'A6',
    model: 'A6M80-1000H2A1-M17',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 3.18,
    peakTorque_Nm: 11.13,
    continuousPower_W: 1000,
    inertia_kgm2: 2.23e-4,
    mass_kg: 2.8,
    frameSize_mm: 80,
    flange_mm: 80,
    shaftDiameter_mm: 19,
    voltage_V: 220,
    current_A: 6.3,
    poleCount: 10,
    encoder: '17-bit single-turn magnetic absolute',
    protectionRating: 'IP67',
    resistance_ohm: 0.35,
    inductance_mH: 2.04,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/a6-series-1000w-ethercat-ac-servo-motor-kit-3000rpm-3-18nm-17-bit-absolute-encoder-ip67-a6-ec1000h2a1-m17',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'omc-t6m80-750h2a1-m23',
    name: 'OMC T6M80-750H2A1-M23 (750W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'T6',
    model: 'T6M80-750H2A1-M23',
    ratedRPM: 3000,
    maxRPM: 5000,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 7.17,
    continuousPower_W: 750,
    inertia_kgm2: 1.5e-4,
    mass_kg: 2.12,
    frameSize_mm: 80,
    flange_mm: 80,
    shaftDiameter_mm: 19,
    voltage_V: 220,
    current_A: 4.1,
    poleCount: 10,
    encoder: '23-bit magnetic absolute',
    protectionRating: 'IP67',
    resistance_ohm: 1.7,
    inductance_mH: 8,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/t6-series-750w-ac-servo-motor-kit-3000rpm-2-39nm-23-bit-encoder-ip67-t6-rs750h2a1-m23',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'omc-t6m80-1000h2a1-m23',
    name: 'OMC T6M80-1000H2A1-M23 (1000W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'T6',
    model: 'T6M80-1000H2A1-M23',
    ratedRPM: 3000,
    maxRPM: 5000,
    ratedTorque_Nm: 3.18,
    peakTorque_Nm: 9.54,
    continuousPower_W: 1000,
    inertia_kgm2: 2e-4,
    mass_kg: 2.8,
    frameSize_mm: 80,
    flange_mm: 80,
    shaftDiameter_mm: 19,
    voltage_V: 220,
    current_A: 5.7,
    poleCount: 10,
    encoder: '23-bit magnetic absolute',
    protectionRating: 'IP67',
    resistance_ohm: 1.08,
    inductance_mH: 5.6,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/t6-series-1000w-ac-servo-motor-kit-3000rpm-3-18nm-23-bit-encoder-ip67-t6-rs1000h2a1-m23',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'omc-t7m60-400h2a1-m23',
    name: 'OMC T7M60-400H2A1-M23 (400W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'T7',
    model: 'T7M60-400H2A1-M23',
    ratedRPM: 3000,
    maxRPM: 5000,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 3.81,
    continuousPower_W: 400,
    inertia_kgm2: 5.6e-5,
    mass_kg: 1.3,
    frameSize_mm: 60,
    flange_mm: 60,
    shaftDiameter_mm: 14,
    voltage_V: 220,
    current_A: 2.1,
    poleCount: 10,
    encoder: '23-bit magnetic',
    protectionRating: 'IP67',
    resistance_ohm: 5.7,
    inductance_mH: 12,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/t7-series-ethercat-400w-ac-servo-motor-kit-3000rpm-1-27nm-23-bit-encoder-ip67-t7-ec400h2a1-m23',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'omc-t7m80-750h2a1-m23',
    name: 'OMC T7M80-750H2A1-M23 (750W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'T7',
    model: 'T7M80-750H2A1-M23',
    ratedRPM: 3000,
    maxRPM: 5000,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 7.17,
    continuousPower_W: 750,
    inertia_kgm2: 1.5e-4,
    mass_kg: 2.12,
    frameSize_mm: 80,
    flange_mm: 80,
    shaftDiameter_mm: 19,
    voltage_V: 220,
    current_A: 4.1,
    poleCount: 10,
    encoder: '23-bit magnetic',
    protectionRating: 'IP67',
    resistance_ohm: 1.7,
    inductance_mH: 8,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/t7-series-ethercat-750w-ac-servo-motor-kit-3000rpm-2-39nm-23-bit-encoder-ip67-t7-ec750h2a1-m23',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'omc-e6m60-400h2a2-m17s',
    name: 'OMC E6M60-400H2A2-M17S (400W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'E6',
    model: 'E6M60-400H2A2-M17S',
    ratedRPM: 3000,
    maxRPM: 6500,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 3.81,
    continuousPower_W: 400,
    inertia_kgm2: 5.6e-5,
    mass_kg: 1.25,
    frameSize_mm: 60,
    flange_mm: 60,
    shaftDiameter_mm: 14,
    voltage_V: 220,
    current_A: 2.1,
    poleCount: 5,
    encoder: '17-bit magnetic incremental',
    protectionRating: 'IP65',
    resistance_ohm: 6.02,
    inductance_mH: 6.63,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/e6-series-400w-ac-servo-motor-kit-3000rpm-1-27nm-17-bit-encoder-ip65-e6-rs400h2a2-m17s',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'omc-e6m80-750h2a2-m17s',
    name: 'OMC E6M80-750H2A2-M17S (750W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'E6',
    model: 'E6M80-750H2A2-M17S',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 7.17,
    continuousPower_W: 750,
    inertia_kgm2: 1.56e-4,
    mass_kg: 2.3,
    frameSize_mm: 80,
    flange_mm: 80,
    shaftDiameter_mm: 19,
    voltage_V: 220,
    current_A: 3.8,
    poleCount: 5,
    encoder: '17-bit magnetic incremental',
    protectionRating: 'IP65',
    resistance_ohm: 1.72,
    inductance_mH: 7.86,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/e6-series-750w-ac-servo-motor-kit-3000rpm-2-39nm-17-bit-encoder-ip65-e6-rs750h2a2-m17s',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'omc-e6m80-1000h2a2-m17s',
    name: 'OMC E6M80-1000H2A2-M17S (1000W)',
    manufacturer: 'StepperOnline',
    motorType: 'ac-servo',
    series: 'E6',
    model: 'E6M80-1000H2A2-M17S',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 3.18,
    peakTorque_Nm: 9.54,
    continuousPower_W: 1000,
    inertia_kgm2: 2e-4,
    mass_kg: 2.75,
    frameSize_mm: 80,
    flange_mm: 80,
    shaftDiameter_mm: 19,
    voltage_V: 220,
    current_A: 5.7,
    poleCount: 5,
    encoder: '17-bit magnetic incremental',
    protectionRating: 'IP65',
    resistance_ohm: 1.1,
    inductance_mH: 0.64,
    datasheetPath: 'docs/motors/stepperonline/official-servo-source-notes.md',
    productUrl:
      'https://www.omc-stepperonline.com/e6-series-1000w-ac-servo-motor-kit-3000rpm-3-18nm-17-bit-encoder-ip65-e6-rs1000h2a2-m17s',
    sourceNote: 'StepperOnline product page spec snapshot.',
    source: 'builtin',
  },
  {
    id: 'delta-ecm-b3m-c20602rs1',
    name: 'Delta ECM-B3M-C20602RS1 (200W)',
    manufacturer: 'Delta',
    motorType: 'ac-servo',
    series: 'ECM-B3M / ASDA-B3',
    model: 'ECM-B3M-C20602RS1',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 0.64,
    peakTorque_Nm: 2.24,
    continuousPower_W: 200,
    inertia_kgm2: 1.41e-5,
    mass_kg: 0.9,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 220,
    encoder: '24-bit incremental',
    datasheetPath: 'docs/motors/delta/asda-b3/200w-techdata.pdf',
    datasheetUrl: 'https://www.rocketronics.de/download/datasheet/delta/200W-techdata.pdf',
    sourceNote: 'Delta B3 200 W techdata PDF.',
    source: 'builtin',
  },
  {
    id: 'delta-ecm-b3m-c20604rs1',
    name: 'Delta ECM-B3M-C20604RS1 (400W)',
    manufacturer: 'Delta',
    motorType: 'ac-servo',
    series: 'ECM-B3M / ASDA-B3',
    model: 'ECM-B3M-C20604RS1',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 4.45,
    continuousPower_W: 400,
    inertia_kgm2: 2.54e-5,
    mass_kg: 1.2,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 220,
    encoder: '24-bit incremental',
    datasheetPath: 'docs/motors/delta/asda-b3/400w-techdata.pdf',
    datasheetUrl: 'https://www.rocketronics.de/download/datasheet/delta/400W-techdata.pdf',
    sourceNote: 'Delta B3 400 W techdata PDF.',
    source: 'builtin',
  },
  {
    id: 'delta-ecm-b3m-c20807rs1',
    name: 'Delta ECM-B3M-C20807RS1 (750W)',
    manufacturer: 'Delta',
    motorType: 'ac-servo',
    series: 'ECM-B3M / ASDA-B3',
    model: 'ECM-B3M-C20807RS1',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 2.4,
    peakTorque_Nm: 8.4,
    continuousPower_W: 750,
    inertia_kgm2: 1.07e-4,
    mass_kg: 2.34,
    frameSize_mm: 80,
    flange_mm: 80,
    voltage_V: 220,
    encoder: '24-bit incremental',
    datasheetPath: 'docs/motors/delta/asda-b3/750w-techdata.pdf',
    datasheetUrl: 'https://www.rocketronics.de/download/datasheet/delta/750W-techdata.pdf',
    sourceNote: 'Delta B3 750 W techdata PDF.',
    source: 'builtin',
  },
  {
    id: 'panasonic-mhmf022l1v2',
    name: 'Panasonic MHMF022L1V2 (200W)',
    manufacturer: 'Panasonic',
    motorType: 'ac-servo',
    series: 'MINAS A6 MHMF',
    model: 'MHMF022L1V2',
    ratedRPM: 3000,
    maxRPM: 6500,
    ratedTorque_Nm: 0.64,
    peakTorque_Nm: 2.23,
    continuousPower_W: 200,
    inertia_kgm2: 3.1e-5,
    voltage_V: 200,
    encoder: '23-bit absolute',
    datasheetPath: 'docs/motors/panasonic/minas-a6/minas-a6-reference.pdf',
    datasheetUrl:
      'https://mediap.industry.panasonic.eu/assets/download-files/import/mn_minas_a6_all_types_reference_pidsx_en.pdf',
    sourceNote: 'Panasonic MINAS A6 all-types reference PDF.',
    source: 'builtin',
  },
  {
    id: 'panasonic-mhmf042l1v2',
    name: 'Panasonic MHMF042L1V2 (400W)',
    manufacturer: 'Panasonic',
    motorType: 'ac-servo',
    series: 'MINAS A6 MHMF',
    model: 'MHMF042L1V2',
    ratedRPM: 3000,
    maxRPM: 6500,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 4.46,
    continuousPower_W: 400,
    inertia_kgm2: 5.8e-5,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 200,
    encoder: '23-bit absolute',
    datasheetPath: 'docs/motors/panasonic/minas-a6/minas-a6-reference.pdf',
    datasheetUrl:
      'https://mediap.industry.panasonic.eu/assets/download-files/import/mn_minas_a6_all_types_reference_pidsx_en.pdf',
    sourceNote: 'Panasonic MINAS A6 all-types reference PDF.',
    source: 'builtin',
  },
  {
    id: 'panasonic-mhmf082l1v2',
    name: 'Panasonic MHMF082L1V2 (750W)',
    manufacturer: 'Panasonic',
    motorType: 'ac-servo',
    series: 'MINAS A6 MHMF',
    model: 'MHMF082L1V2',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 8.36,
    continuousPower_W: 750,
    inertia_kgm2: 1.66e-4,
    voltage_V: 200,
    encoder: '23-bit absolute',
    datasheetPath: 'docs/motors/panasonic/minas-a6/minas-a6-reference.pdf',
    datasheetUrl:
      'https://mediap.industry.panasonic.eu/assets/download-files/import/mn_minas_a6_all_types_reference_pidsx_en.pdf',
    sourceNote: 'Panasonic MINAS A6 all-types reference PDF.',
    source: 'builtin',
  },
  {
    id: 'yaskawa-sgm7j-02afa21',
    name: 'Yaskawa SGM7J-02AFA21 (200W)',
    manufacturer: 'Yaskawa',
    motorType: 'ac-servo',
    series: 'Sigma-7 SGM7J',
    model: 'SGM7J-02AFA21',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 0.637,
    peakTorque_Nm: 2.23,
    continuousPower_W: 200,
    inertia_kgm2: 2.63e-5,
    mass_kg: 0.8,
    frameSize_mm: 50,
    flange_mm: 50,
    voltage_V: 200,
    encoder: '24-bit absolute',
    datasheetPath: 'docs/motors/yaskawa/sigma-7/sigma-7-brochure.pdf',
    datasheetUrl:
      'https://www.yaskawa.com/delegate/getAttachment?documentId=BL.Sigma-7.01&cmd=documents&openNewTab=true&documentName=BL.Sigma-7.01.pdf',
    sourceNote: 'Yaskawa Sigma-7 brochure and product data.',
    source: 'builtin',
  },
  {
    id: 'yaskawa-sgm7j-04a6a61',
    name: 'Yaskawa SGM7J-04A6A61 (400W)',
    manufacturer: 'Yaskawa',
    motorType: 'ac-servo',
    series: 'Sigma-7 SGM7J',
    model: 'SGM7J-04A6A61',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 4.46,
    continuousPower_W: 400,
    inertia_kgm2: 4.87e-5,
    mass_kg: 1.1,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 200,
    hasBrake: false,
    encoder: '24-bit absolute',
    datasheetPath: 'docs/motors/yaskawa/sigma-7/sigma-7-brochure.pdf',
    datasheetUrl:
      'https://www.yaskawa.com/delegate/getAttachment?documentId=BL.Sigma-7.01&cmd=documents&openNewTab=true&documentName=BL.Sigma-7.01.pdf',
    sourceNote: 'Yaskawa Sigma-7 brochure and product data.',
    source: 'builtin',
  },
  {
    id: 'yaskawa-sgm7j-08a7a21',
    name: 'Yaskawa SGM7J-08A7A21 (750W)',
    manufacturer: 'Yaskawa',
    motorType: 'ac-servo',
    series: 'Sigma-7 SGM7J',
    model: 'SGM7J-08A7A21',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 8.36,
    continuousPower_W: 750,
    inertia_kgm2: 1.59e-4,
    mass_kg: 2.2,
    frameSize_mm: 80,
    flange_mm: 80,
    voltage_V: 200,
    encoder: '24-bit absolute',
    datasheetPath: 'docs/motors/yaskawa/sigma-7/sigma-7-brochure.pdf',
    datasheetUrl:
      'https://www.yaskawa.com/delegate/getAttachment?documentId=BL.Sigma-7.01&cmd=documents&openNewTab=true&documentName=BL.Sigma-7.01.pdf',
    sourceNote: 'Yaskawa Sigma-7 brochure and product data.',
    source: 'builtin',
  },
  {
    id: 'mitsubishi-hk-kt23w',
    name: 'Mitsubishi HK-KT23W (200W)',
    manufacturer: 'Mitsubishi',
    motorType: 'ac-servo',
    series: 'MELSERVO-J5 HK-KT',
    model: 'HK-KT23W',
    ratedRPM: 3000,
    maxRPM: 6700,
    ratedTorque_Nm: 0.64,
    peakTorque_Nm: 2.2,
    continuousPower_W: 200,
    inertia_kgm2: 2.09e-5,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 200,
    hasBrake: false,
    encoder: '26-bit absolute',
    datasheetPath: 'docs/motors/mitsubishi/melservo-j5/mr-j5-rotary-servo-manual.pdf',
    datasheetUrl: 'https://dl.mitsubishielectric.com/dl/fa/document/manual/servo/sh030298eng/sh030298engn.pdf',
    sourceNote: 'Mitsubishi MR-J5 rotary servo motor manual.',
    source: 'builtin',
  },
  {
    id: 'mitsubishi-hk-kt43w',
    name: 'Mitsubishi HK-KT43W (400W)',
    manufacturer: 'Mitsubishi',
    motorType: 'ac-servo',
    series: 'MELSERVO-J5 HK-KT',
    model: 'HK-KT43W',
    ratedRPM: 3000,
    maxRPM: 6700,
    ratedTorque_Nm: 1.3,
    peakTorque_Nm: 4.5,
    continuousPower_W: 400,
    inertia_kgm2: 4.1e-5,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 200,
    hasBrake: false,
    encoder: '26-bit absolute',
    datasheetPath: 'docs/motors/mitsubishi/melservo-j5/mr-j5-rotary-servo-manual.pdf',
    datasheetUrl: 'https://dl.mitsubishielectric.com/dl/fa/document/manual/servo/sh030298eng/sh030298engn.pdf',
    sourceNote: 'Mitsubishi MR-J5 rotary servo motor manual.',
    source: 'builtin',
  },
  {
    id: 'mitsubishi-hk-st52w',
    name: 'Mitsubishi HK-ST52W (500W)',
    manufacturer: 'Mitsubishi',
    motorType: 'ac-servo',
    series: 'MELSERVO-J5 HK-ST',
    model: 'HK-ST52W',
    ratedRPM: 2000,
    maxRPM: 4000,
    ratedTorque_Nm: 2.4,
    peakTorque_Nm: 7.2,
    continuousPower_W: 500,
    inertia_kgm2: 5.9e-4,
    frameSize_mm: 130,
    flange_mm: 130,
    voltage_V: 200,
    hasBrake: false,
    encoder: '26-bit absolute',
    datasheetPath: 'docs/motors/mitsubishi/melservo-j5/mr-j5-rotary-servo-manual.pdf',
    datasheetUrl: 'https://dl.mitsubishielectric.com/dl/fa/document/manual/servo/sh030298eng/sh030298engn.pdf',
    sourceNote: 'Mitsubishi MR-J5 rotary servo motor manual.',
    source: 'builtin',
  },
  {
    id: 'mitsubishi-hk-kt7m3w',
    name: 'Mitsubishi HK-KT7M3W (750W)',
    manufacturer: 'Mitsubishi',
    motorType: 'ac-servo',
    series: 'MELSERVO-J5 HK-KT',
    model: 'HK-KT7M3W',
    ratedRPM: 3000,
    maxRPM: 6700,
    ratedTorque_Nm: 2.4,
    peakTorque_Nm: 8.4,
    continuousPower_W: 750,
    inertia_kgm2: 1.37e-4,
    frameSize_mm: 80,
    flange_mm: 80,
    voltage_V: 200,
    hasBrake: false,
    encoder: '26-bit absolute',
    datasheetPath: 'docs/motors/mitsubishi/melservo-j5/mr-j5-rotary-servo-manual.pdf',
    datasheetUrl: 'https://dl.mitsubishielectric.com/dl/fa/document/manual/servo/sh030298eng/sh030298engn.pdf',
    sourceNote: 'Mitsubishi MR-J5 rotary servo motor manual.',
    source: 'builtin',
  },
  {
    id: 'mitsubishi-hk-st102w',
    name: 'Mitsubishi HK-ST102W (1000W)',
    manufacturer: 'Mitsubishi',
    motorType: 'ac-servo',
    series: 'MELSERVO-J5 HK-ST',
    model: 'HK-ST102W',
    ratedRPM: 2000,
    maxRPM: 4000,
    ratedTorque_Nm: 4.8,
    peakTorque_Nm: 14.3,
    continuousPower_W: 1000,
    inertia_kgm2: 8.65e-4,
    frameSize_mm: 130,
    flange_mm: 130,
    voltage_V: 200,
    hasBrake: false,
    encoder: '26-bit absolute',
    datasheetPath: 'docs/motors/mitsubishi/melservo-j5/mr-j5-rotary-servo-manual.pdf',
    datasheetUrl: 'https://dl.mitsubishielectric.com/dl/fa/document/manual/servo/sh030298eng/sh030298engn.pdf',
    sourceNote: 'Mitsubishi MR-J5 rotary servo motor manual.',
    source: 'builtin',
  },
  {
    id: 'leadshine-isv2-rs6020v48h',
    name: 'Leadshine iSV2-RS6020V48H (200W)',
    manufacturer: 'Leadshine',
    motorType: 'step-servo',
    series: 'iSV2-RS',
    model: 'iSV2-RS6020V48H',
    ratedRPM: 3000,
    maxRPM: 4000,
    ratedTorque_Nm: 0.64,
    peakTorque_Nm: 1.92,
    continuousPower_W: 200,
    inertia_kgm2: 2.8e-5,
    mass_kg: 1.1,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 48,
    hasBrake: true,
    encoder: '17-bit incremental magnetic encoder',
    datasheetPath: 'docs/motors/leadshine/isv2-rs/isv2-rs6020v48h.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/346a5e1da75c2223a6bbf587e7ac828a_1711076706568.pdf',
    productUrl: 'https://www.leadshine.com/network-detail/fieldbus/Modbus-RTU/iSV2-RS6020V48H.html',
    sourceNote: 'Leadshine product page and technical data PDF.',
    notes: 'Integrated motor and drive package.',
    source: 'builtin',
  },
  {
    id: 'leadshine-isv2-rs6040v48h',
    name: 'Leadshine iSV2-RS6040V48H (400W)',
    manufacturer: 'Leadshine',
    motorType: 'step-servo',
    series: 'iSV2-RS',
    model: 'iSV2-RS6040V48H',
    ratedRPM: 3000,
    maxRPM: 4000,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 3.81,
    continuousPower_W: 400,
    inertia_kgm2: 5.6e-5,
    mass_kg: 1.26,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 48,
    hasBrake: true,
    encoder: '17-bit incremental magnetic encoder',
    datasheetPath: 'docs/motors/leadshine/isv2-rs/isv2-rs6040v48h.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/4aaeadb60895dc31ff5617136672ba41_1711076869412.pdf',
    productUrl: 'https://www.leadshine.com/network-detail/fieldbus/Modbus-RTU/iSV2-RS6040V48H.html',
    sourceNote: 'Leadshine product page and technical data PDF.',
    notes: 'Integrated motor and drive package.',
    source: 'builtin',
  },
  {
    id: 'leadshine-isv2-rs8075v48h',
    name: 'Leadshine iSV2-RS8075V48H (750W)',
    manufacturer: 'Leadshine',
    motorType: 'step-servo',
    series: 'iSV2-RS',
    model: 'iSV2-RS8075V48H',
    ratedRPM: 3000,
    maxRPM: 4000,
    ratedTorque_Nm: 2.4,
    peakTorque_Nm: 7.2,
    continuousPower_W: 750,
    inertia_kgm2: 1.5e-4,
    mass_kg: 2.52,
    frameSize_mm: 80,
    flange_mm: 80,
    voltage_V: 48,
    hasBrake: true,
    encoder: '17-bit incremental magnetic encoder',
    datasheetPath: 'docs/motors/leadshine/isv2-rs/isv2-rs8075v48h.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/e22060f63400880925a409fb8252e961_1716280169667.pdf',
    productUrl: 'https://www.leadshine.com/network-detail/fieldbus/Modbus-RTU/iSV2-RS8075V48H.html',
    sourceNote: 'Leadshine product page and technical data PDF.',
    notes: 'Integrated motor and drive package.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elm1h-0200ma60f',
    name: 'Leadshine ELM1H-0200MA60F (200W)',
    manufacturer: 'Leadshine',
    motorType: 'ac-servo',
    series: 'ELM1',
    model: 'ELM1H-0200MA60F',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 0.64,
    peakTorque_Nm: 1.92,
    continuousPower_W: 200,
    inertia_kgm2: 2.8e-5,
    mass_kg: 1,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 220,
    encoder: '23-bit magnetic',
    datasheetPath: 'docs/motors/leadshine/elm1/elm1h-0200ma60f.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/0cc86e2b7bb2f3acc9f8f17a538a44ba_1776049773388.pdf',
    productUrl: 'https://www.leadshine.com/product-detail/e-servo-drives/EtherCAT/ELM1H-0200MA60F.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elm1h-0400ma60f',
    name: 'Leadshine ELM1H-0400MA60F (400W)',
    manufacturer: 'Leadshine',
    motorType: 'ac-servo',
    series: 'ELM1',
    model: 'ELM1H-0400MA60F',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 3.81,
    continuousPower_W: 400,
    inertia_kgm2: 5.6e-5,
    mass_kg: 1.3,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 220,
    encoder: '23-bit magnetic',
    datasheetPath: 'docs/motors/leadshine/elm1/elm1h-0400ma60f.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/097b10e51077b9464c928a6eeed46b45_1776050106692.pdf',
    productUrl: 'https://www.leadshine.com/product-detail/e-servo-drives/EtherCAT/ELM1H-0400MA60F.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elm1h-0750ma80f',
    name: 'Leadshine ELM1H-0750MA80F (750W)',
    manufacturer: 'Leadshine',
    motorType: 'ac-servo',
    series: 'ELM1',
    model: 'ELM1H-0750MA80F',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 7.17,
    continuousPower_W: 750,
    inertia_kgm2: 1.5e-4,
    mass_kg: 2.12,
    frameSize_mm: 80,
    flange_mm: 80,
    voltage_V: 220,
    encoder: '23-bit magnetic',
    datasheetPath: 'docs/motors/leadshine/elm1/elm1h-0750ma80f.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/70701780cd26cb07a4077619781b9804_1776050310626.pdf',
    productUrl: 'https://www.leadshine.com/product/ELM1H-0750MA80F%20Servo%20Motor-4-20-650-40.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elm1h-1000ma80f',
    name: 'Leadshine ELM1H-1000MA80F (1000W)',
    manufacturer: 'Leadshine',
    motorType: 'ac-servo',
    series: 'ELM1',
    model: 'ELM1H-1000MA80F',
    ratedRPM: 3000,
    maxRPM: 6000,
    ratedTorque_Nm: 3.18,
    peakTorque_Nm: 9.54,
    continuousPower_W: 1000,
    inertia_kgm2: 2e-4,
    mass_kg: 2.8,
    frameSize_mm: 80,
    flange_mm: 80,
    voltage_V: 220,
    encoder: '23-bit magnetic',
    datasheetPath: 'docs/motors/leadshine/elm1/elm1h-1000ma80f.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/0de71adc5eff29ea76352213a30d38d5_1776050487481.pdf',
    productUrl: 'https://www.leadshine.com/product-detail/e-servo-drives/EtherCAT/ELM1H-1000MA80F.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elm2h-0200la60f',
    name: 'Leadshine ELM2H-0200LA60F (200W)',
    manufacturer: 'Leadshine',
    motorType: 'ac-servo',
    series: 'ELM2',
    model: 'ELM2H-0200LA60F',
    ratedRPM: 3000,
    maxRPM: 6500,
    ratedTorque_Nm: 0.64,
    peakTorque_Nm: 1.92,
    continuousPower_W: 200,
    inertia_kgm2: 2.8e-5,
    mass_kg: 0.95,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 220,
    encoder: '23-bit optical',
    datasheetPath: 'docs/motors/leadshine/elm2/elm2h-0200la60f.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/311134d4a2e9f48fedce9cefd6e6783b_1776050981298.pdf',
    productUrl: 'https://www.leadshine.com/product-detail/e-servo-drives/EtherCAT/ELM2H-0200LA60F.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elm2h-0400la60f',
    name: 'Leadshine ELM2H-0400LA60F (400W)',
    manufacturer: 'Leadshine',
    motorType: 'ac-servo',
    series: 'ELM2',
    model: 'ELM2H-0400LA60F',
    ratedRPM: 3000,
    maxRPM: 6500,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 3.81,
    continuousPower_W: 400,
    inertia_kgm2: 5.6e-5,
    mass_kg: 1.3,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 220,
    encoder: '23-bit optical',
    datasheetPath: 'docs/motors/leadshine/elm2/elm2h-0400la60f.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/d95198671f1e8fe14a9f7e925b836e20_1776051123893.pdf',
    productUrl: 'https://www.leadshine.com/product-detail/e-servo-drives/EtherCAT/ELM2H-0400LA60F.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elm2h-0750la80f',
    name: 'Leadshine ELM2H-0750LA80F (750W)',
    manufacturer: 'Leadshine',
    motorType: 'ac-servo',
    series: 'ELM2',
    model: 'ELM2H-0750LA80F',
    ratedRPM: 3000,
    maxRPM: 6500,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 7.17,
    continuousPower_W: 750,
    inertia_kgm2: 1.5e-4,
    mass_kg: 2.1,
    frameSize_mm: 80,
    flange_mm: 80,
    voltage_V: 220,
    encoder: '23-bit optical',
    datasheetPath: 'docs/motors/leadshine/elm2/elm2h-0750la80f.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/e74ce75a6026c8414e6e8b501b406857_1776051273833.pdf',
    productUrl: 'https://www.leadshine.com/product-detail/servo-drive/servo/ELM2H-0750LA80F.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elm2h-1000la80f',
    name: 'Leadshine ELM2H-1000LA80F (1000W)',
    manufacturer: 'Leadshine',
    motorType: 'ac-servo',
    series: 'ELM2',
    model: 'ELM2H-1000LA80F',
    ratedRPM: 3000,
    maxRPM: 6500,
    ratedTorque_Nm: 3.18,
    peakTorque_Nm: 9.54,
    continuousPower_W: 1000,
    inertia_kgm2: 2e-4,
    mass_kg: 2.8,
    frameSize_mm: 80,
    flange_mm: 80,
    voltage_V: 220,
    encoder: '23-bit optical',
    datasheetPath: 'docs/motors/leadshine/elm2/elm2h-1000la80f.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/e7819e29807893eb51247a98fd3b1808_1776051408133.pdf',
    productUrl: 'https://www.leadshine.com/product-detail/e-servo-drives/EtherCAT/ELM2H-1000LA80F.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elvm6040v48fh-m17-hd',
    name: 'Leadshine ELVM6040V48FH-M17-HD (400W)',
    manufacturer: 'Leadshine',
    motorType: 'bldc-servo',
    series: 'ELVM',
    model: 'ELVM6040V48FH-M17-HD',
    ratedRPM: 3000,
    maxRPM: 4000,
    ratedTorque_Nm: 1.27,
    peakTorque_Nm: 3.81,
    continuousPower_W: 400,
    inertia_kgm2: 5.8e-5,
    mass_kg: 1.3,
    frameSize_mm: 60,
    flange_mm: 60,
    voltage_V: 48,
    hasBrake: false,
    encoder: '17-bit magnetic',
    datasheetPath: 'docs/motors/leadshine/elvm/elvm6040v48fh-m17-hd.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/714e1eaef5287b313d7c5a556336cf83_1689761294780.pdf',
    productUrl: 'https://www.leadshine.com/product/ELVM6040V48FH-M17-HD-4-20-171-30.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
  {
    id: 'leadshine-elvm8075v48fh-m17-hd',
    name: 'Leadshine ELVM8075V48FH-M17-HD (750W)',
    manufacturer: 'Leadshine',
    motorType: 'bldc-servo',
    series: 'ELVM',
    model: 'ELVM8075V48FH-M17-HD',
    ratedRPM: 3000,
    maxRPM: 3900,
    ratedTorque_Nm: 2.39,
    peakTorque_Nm: 7.17,
    continuousPower_W: 750,
    inertia_kgm2: 1.5e-4,
    mass_kg: 2.12,
    frameSize_mm: 80,
    flange_mm: 80,
    voltage_V: 48,
    hasBrake: false,
    encoder: '17-bit magnetic',
    datasheetPath: 'docs/motors/leadshine/elvm/elvm8075v48fh-m17-hd.pdf',
    datasheetUrl: 'https://www.leadshine.com/upfiles/downloads/802e3197e07346c74f77537f4615e850_1689761789660.pdf',
    productUrl: 'https://www.leadshine.com/product/ELVM8075V48FH-M17-HD-4-20-157-30.html',
    sourceNote: 'Leadshine product page and model PDF.',
    source: 'builtin',
  },
];

const USER_SERVO_MOTORS_KEY = 'actuator-sizing-user-motors';

function isValidServoMotor(value: unknown): value is ServoMotor {
  if (typeof value !== 'object' || value === null) {
    return false;
  }

  const motor = value as Record<string, unknown>;
  return (
    typeof motor.id === 'string' &&
    typeof motor.name === 'string' &&
    typeof motor.ratedRPM === 'number' &&
    typeof motor.maxRPM === 'number' &&
    typeof motor.ratedTorque_Nm === 'number' &&
    typeof motor.peakTorque_Nm === 'number' &&
    typeof motor.continuousPower_W === 'number' &&
    typeof motor.inertia_kgm2 === 'number' &&
    motor.source === 'user'
  );
}

export function loadUserServoMotors(): ServoMotor[] {
  if (typeof localStorage === 'undefined') {
    return [];
  }

  try {
    const raw = localStorage.getItem(USER_SERVO_MOTORS_KEY);
    if (!raw) {
      return [];
    }

    const parsed: unknown = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter(isValidServoMotor) : [];
  } catch {
    return [];
  }
}

export function saveUserServoMotors(motors: ServoMotor[]): void {
  if (typeof localStorage === 'undefined') {
    return;
  }

  localStorage.setItem(USER_SERVO_MOTORS_KEY, JSON.stringify(motors.filter((motor) => motor.source === 'user')));
}
