// Generated by scripts/export-human-rigged-model.py.
import type { PlannerAnthropometryLengthsMm, PlannerAnthropometryRatios } from './types';

const DEFAULT_ANTHROPOMETRY_REFERENCE_HEIGHT_CM = 169;

export const DEFAULT_ANTHROPOMETRY_LENGTHS_MM = {
  sittingHeight: 806.1,
  seatedShoulderHeight: 493.5,
  hipBreadth: 207.9,
  shoulderBreadth: 346.4,
  upperArmLength: 238.3,
  forearmHandLength: 329.5,
  thighLength: 419.1,
  lowerLegLength: 390.4,
  footLength: 290.7,
} satisfies PlannerAnthropometryLengthsMm;

export const DEFAULT_ANTHROPOMETRY_HEEL_LENGTH_SHARE = 0.272;

function getDefaultAnthropometryRatio(lengthMm: number) {
  return Number((lengthMm / (DEFAULT_ANTHROPOMETRY_REFERENCE_HEIGHT_CM * 10)).toFixed(3));
}

export const DEFAULT_ANTHROPOMETRY_RATIOS = Object.fromEntries(
  Object.entries(DEFAULT_ANTHROPOMETRY_LENGTHS_MM).map(([key, value]) => [key, getDefaultAnthropometryRatio(value)])
) as PlannerAnthropometryRatios;

export const ANTHROPOMETRY_LENGTH_LIMITS_MM = Object.fromEntries(
  Object.entries(DEFAULT_ANTHROPOMETRY_LENGTHS_MM).map(([key, value]) => [
    key,
    {
      min: Number((value * 0.8).toFixed(1)),
      max: Number((value * 1.2).toFixed(1)),
    },
  ])
) as Record<keyof PlannerAnthropometryRatios, { min: number; max: number }>;
